version: '3'
services:
  manager:
    build:
      context: ./CrackHashManager
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    expose:
      - "8081"
    environment:
      - WORKER_SERVICE_NAME=CrackHashWorker
      - WORKER_SERVICE_PORT=8082
      - MANAGER_SERVICE_PORT=8081
    networks:
      - my-network

  worker:
    build:
      context: ./CrackHashWorker
      dockerfile: Dockerfile
    expose:
      - "8082"
    environment:
      - MANAGER_SERVICE_NAME=CrackHashManager
      - MANAGER_SERVICE_PORT=8081
      - WORKER_SERVICE_PORT=8082
    networks:
      - my-network
networks:
  my-network:
    driver: bridge